//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionPlan()
        {
            this.ActionPlanDecisions = new HashSet<ActionPlanDecision>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SprintCommentId { get; set; }
        public Nullable<int> FollwingUpByMemberId { get; set; }
    
        public virtual SprintComment SprintComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionPlanDecision> ActionPlanDecisions { get; set; }
    }
}
