//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgileMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgileMember()
        {
            this.SprintEvaluations = new HashSet<SprintEvaluation>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public Nullable<int> CurrentTeamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SprintEvaluation> SprintEvaluations { get; set; }
    }
}
