//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprintComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SprintComment()
        {
            this.ActionPlans = new HashSet<ActionPlan>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int SprintCategoryId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public int SprintId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionPlan> ActionPlans { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual SprintCategory SprintCategory { get; set; }
    }
}
