//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStory()
        {
            this.UserStoryAssignmentMembers = new HashSet<UserStoryAssignmentMember>();
        }
    
        public int Id { get; set; }
        public string JiraUrl { get; set; }
        public string Title { get; set; }
        public Nullable<int> CreatedByMemberId { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int SprintId { get; set; }
        public string Description { get; set; }
    
        public virtual Sprint Sprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStoryAssignmentMember> UserStoryAssignmentMembers { get; set; }
    }
}
